name: fancy_bottom_navigation_plus
description: An animated Bottom Navigation Bar for Flutter apps, icon animates into place, colors are customisable..
version: 1.0.0
homepage: https://github.com/jinosh05/fancy_bottom_navigation_plus

environment:
  sdk: ">=2.19.0-204.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
